remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: HSE News Monitor
name: HSENewsMonitor
google_analytics_measurement_id: G-94DYDBLPCL



paginate: 30
paginate_path: "/news/page:num/"
collections:
  authors:

exclude: "/news/index.html"

