name: Download Posts
on:
  workflow_dispatch:
  schedule:
    - cron:  '0/30 * * * *'
  
jobs:
  Custom-Example:
    runs-on: ubuntu-latest
    env:
      bucket: ${{ github.event.inputs.bucket }}
    steps:
      
    
      - name: Check out repository code
        uses: actions/checkout@v2
          
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_TOKEN }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_TOKEN_SECRET }}
          aws-region: eu-west-1
      #- run: aws s3 cp s3://rssfeed/_posts/ ./_posts/ --recursive
      #- run: aws s3 cp s3://rssfeed/_authors/ ./_authors/ --recursive
      
      - run: aws s3 sync s3://rssfeed/_posts/ ./_posts/ --delete
      - run: aws s3 sync s3://rssfeed/_authors/ ./_authors/ --delete
      
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
